default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: metcalf_tools_dev
  username: max
  password: Denmark2015

test:
  <<: *default
  database: metcalf_tools_test
  username: max
  password: Denmark2015

production:
  <<: *default
  username: max
  password: Denmark2015
